theme: jekyll-theme-architect
<<<<<<< HEAD
title: Brilgwae's bric-a-brac
=======
title: Le bric-a-brac de Brilgwae
>>>>>>> parent of 2471e2c... Update _config.yml
description: ca parle de tout, de rien ... surtout de rien
